# default config for minions app

[core]
    # List of directories containing extra plugins
    extra_plugin_directories = []

    # Timeout (in milliseconds) to clear filter text if no more characters is entered
    # Set to 0 to disable
    filter_timeout = 800

    # Keyboard shortcuts to bring up Minions
    shortcut_show = "<Ctrl>space"
    # Keyboard shortcuts to bring up Minions with selected text
    shortcut_show_quicksend = "<Ctrl><Shift>space"

    # Statistic file location
    statistic_file = "~/.local/share/minions/statistic.dat"

    # Hash salt used in statistic file
    # Change this value would make all statistic invalid
    statistic_file_salt = "Minions-Salt"

    # Database location, used by many services (e.g. clipboard history)
    db_file = "~/.local/share/minions/minions.db"

    # Max number of saved history entries (input text) for each action
    history = 10

# list of search engines
# Each site must have `name` and `address` defined
# and optionally `suggestion_url` for suggestions, which follows the OpenSearch standard
[search_engine]
    [[search_engine.sites]]
    name = "Google"
    icon = "fontawesome:google"
    address = "https://www.google.com/search?q=%s"
    suggestion_url = "https://clients1.google.com/complete/search?q=%s&client=chrome"
    [[search_engine.sites]]
    name = "Google I'm Feeling Lucky"
    icon = "fontawesome:google"
    address = "https://www.google.com/search?q=%s&btnI"
    suggestion_url = "https://clients1.google.com/complete/search?q=%s&client=chrome"
    [[search_engine.sites]]
    name = "Bing"
    icon = "fontawesome:microsoft"
    address = "https://www.bing.com/search?q=%s"
    suggestion_url = "https://www.bing.com/osjson.aspx?query=%s"
    [[search_engine.sites]]
    name = "DuckDuckGo"
    address = "https://duckduckgo.com/?q=%s"
    suggestion_url = "https://ac.duckduckgo.com/ac/?q=%s&type=list"
    [[search_engine.sites]]
    name = "Wikipedia"
    icon = "fontawesome:wikipedia-w"
    address = "https://en.wikipedia.org/wiki/Special:Search?search=%s"
    suggestion_url = "https://en.wikipedia.org/w/api.php?action=opensearch&search=%s"
    [[search_engine.sites]]
    name = "WolframAlpha"
    address = "https://www.wolframalpha.com/input/i=%s"

# Linux desktop entries (Applications)
[linux_desktop_entry]
# Directories to find all .desktop files
    directories = [
        "/usr/local/share/applications/",
        "/usr/share/applications/",
    ]

# File Browser
# Each entry must include a `name` and a valid `path` (can be directory or file)
[file_browser]
    [[file_browser.entries]]
    name = "Home Directory"
    path = "~/"
    [[file_browser.entries]]
    name = "Root Directory"
    path = "/"


[clipboard_history]
    # Max number of recent entries to record in history
    max_entries = 64
    # Whether to ignore entries with only single byte (useful if you use vim and press "x" a lot)
    ignore_single_byte = true

[wolframalpha]
    appid = "AT5PY2-5AQXHRXE8K"
